# Generated by Django 4.1 on 2024-01-25 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('openAgri', '0002_device_type_weatherdata_qgisdata_mobiledata'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mobiledata',
            name='device',
        ),
        migrations.RemoveField(
            model_name='qgisdata',
            name='device',
        ),
        migrations.RemoveField(
            model_name='weatherdata',
            name='device',
        ),
        migrations.DeleteModel(
            name='Device',
        ),
        migrations.DeleteModel(
            name='MobileData',
        ),
        migrations.DeleteModel(
            name='QgisData',
        ),
        migrations.DeleteModel(
            name='WeatherData',
        ),
    ]
