# Generated by Django 4.1 on 2024-01-25 21:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('macaddress', models.CharField(max_length=100)),
                ('type', models.IntegerField(null=True)),
                ('users', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WeatherData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geo_location_lat', models.FloatField(null=True)),
                ('geo_location_long', models.FloatField(null=True)),
                ('wind_direction', models.CharField(max_length=128, null=True)),
                ('wind_speed', models.CharField(max_length=128, null=True)),
                ('rainfall', models.CharField(max_length=128, null=True)),
                ('sunshine', models.CharField(max_length=128, null=True)),
                ('temperature', models.CharField(max_length=128, null=True)),
                ('humidity', models.CharField(max_length=128, null=True)),
                ('recording_time', models.DateTimeField()),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.device')),
            ],
        ),
        migrations.CreateModel(
            name='QgisData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geo_location_lat', models.FloatField(null=True)),
                ('geo_location_long', models.FloatField(null=True)),
                ('ndvi', models.FloatField(null=True)),
                ('gndvi', models.FloatField(null=True)),
                ('lai', models.FloatField(null=True)),
                ('msdvi', models.FloatField(null=True)),
                ('recording_time', models.DateTimeField()),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.device')),
            ],
        ),
        migrations.CreateModel(
            name='MobileData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geo_location_lat', models.FloatField(null=True)),
                ('geo_location_long', models.FloatField(null=True)),
                ('image_path', models.CharField(max_length=256)),
                ('qr_code', models.TextField()),
                ('recording_time', models.DateTimeField(null=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.device')),
            ],
        ),
    ]
